title: Hello, world! I'm Zhuang Kang
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Zhuang Kang # add your name
author-img: WechatIMG139.jpg # add your photo
about-author: I am Zhuang Kang, currently pursuing a Master's degree in Mathematics at the University of Münster. My research interests lie in the intersection of mathematical image processing, optimization, and machine learning. # add description
social-github: Proskahn # add your Github handle
# social-kaggle: zhuangkang 
social-linkedin: zhuang-kang-223205224 # add your Linkedin handle
social-email: z.kang@uni-muenster.de # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
